# Image de base Python
FROM python:3.11-slim

# Définit le répertoire de travail
WORKDIR /app

# Copie le fichier requirements.txt
COPY ../backend/requirements.txt .

# Installe les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le code du backend
COPY ../backend/ .

# Crée le dossier uploads
RUN mkdir -p uploads

# Expose le port 8000
EXPOSE 8000

# Commande pour lancer l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]